package de.esailors.dataheart.drillviews.data;

import java.util.Collection;

import org.apache.avro.Schema;

import com.google.common.base.Optional;

public class EventStructureSource {

	public enum Type {
		EVENT, AVRO_SCHEMA, STRUCTURE_MERGE
	}

	private Type type;

	private Event sourceEvent; // for structures generated from json events
	private Collection<EventStructure> sourceStructures; // for structures generated by merges
	private AvroSchema sourceSchema; // for structures generated from avro schemas

	public EventStructureSource(Event sourceEvent) {
		type = Type.EVENT;
		this.sourceEvent = sourceEvent;
	}

	public EventStructureSource(AvroSchema sourceSchema) {
		type = Type.AVRO_SCHEMA;
		this.sourceSchema = sourceSchema;
	}

	public EventStructureSource(Collection<EventStructure> sourceStructures) {
		type = Type.STRUCTURE_MERGE;
		this.sourceStructures = sourceStructures;
	}

	public Type getType() {
		return type;
	}
	
	public Optional<Event> getSourceEvent() {
		return Optional.fromNullable(sourceEvent);
	}

	public Optional<AvroSchema> getSourceSchema() {
		return Optional.fromNullable(sourceSchema);
	}
	
	public Optional<Collection<EventStructure>> getSourceStructures() {
		return Optional.fromNullable(sourceStructures);
	}

	@Override
	public String toString() {
		String r = getType().toString();
		switch (type) {
		case EVENT: {
			r += "_" + sourceEvent.readSchemaVersion() + "_" + sourceEvent.hashCode();
			break;
		}
		case AVRO_SCHEMA: {
			r += "_" + sourceSchema.getSchema().getFullName();
			break;
		}
		case STRUCTURE_MERGE: {
			for(EventStructure sourceStructure : sourceStructures) {
				r += "_" + sourceStructure.hashCode();
			}
			break;
		}
		}
		return r;
	}

}
